Repository okp4/dataverse-portal, pull requests merged in 2023-08, with the labels that each got.

#436 fix(share): fix order in file list
  src/ui/component/list/list.scss
  src/ui/component/list/list.tsx
  src/ui/page/share/dataset/steps/dataSelection/dataSelection.tsx
Labels: bug 🐞

#435 Feat/share data slice v2
  src/domain/file/command.ts
  src/domain/file/domain.ts
  src/domain/file/test/removeFile.spec.ts
  src/domain/file/test/storeFiles.spec.ts
  src/shared/error/payload.ts
  src/shared/error/resource.ts
  src/ui/page/share/dataset/steps/dataSelection/dataSelection.tsx
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
  src/ui/store/appStore.ts
  src/ui/store/slice/shareData/shareData.slice.ts
  src/ui/store/slice/shareData/test/shareData.slice.spec.ts
  src/ui/store/slice/shareData/test/shareDataSlice.spec.ts
  src/util/util.spec.ts
  src/util/util.ts
Labels: feature 🤌

#434 Feat/add modal
  src/ui/App.tsx
  src/ui/component/modal/modal.scss
  src/ui/component/modal/modal.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
Labels: feature 🤌

#440 fix(dataverse): add missing dataset
  src/ui/page/dataverse/dataverse.tsx
Labels: bug 🐞

#441 Style/update button
  src/ui/component/button/button.scss
  src/ui/component/button/button.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
Labels: enhancement 💯

#438 feat: add okp4 modal
  src/ui/component/modal/modal.scss
  src/ui/component/modal/modal.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
  src/ui/view/modal/okp4-modal.scss
  src/ui/view/modal/okp4-modal.tsx
Labels: feature 🤌

#437 feat(filePicker): add folder drag and drop management
  src/ui/component/filePicker/filePicker.tsx
Labels: enhancement 💯

#442 Feat/popover component
  package.json
  pnpm-lock.yaml
  src/ui/App.tsx
  src/ui/component/collapsible/collapsible.scss
  src/ui/component/popover/popover.scss
  src/ui/component/popover/popover.tsx
Labels: feature 🤌

#430 Feat/numerical input field
  package.json
  pnpm-lock.yaml
  src/ui/component/field/baseField.tsx
  src/ui/component/field/field.scss
  src/ui/component/field/field.tsx
  src/ui/component/field/numericField.tsx
  src/ui/component/field/textField.tsx
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
  src/util/i18n/i18n.spec.ts
  src/util/i18n/i18n.ts
  src/util/util.spec.ts
  src/util/util.ts
Labels: feature 🤌

#452 Feat/add know fee wrapper in sharedata step3
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
Labels: feature 🤌

#444 Refactor/make dropdown component generic
  src/ui/component/dropDown/dropDown.scss
  src/ui/component/dropDown/dropDown.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
  src/ui/view/share/data/dropDown/dropDown.scss
  src/ui/view/share/data/dropDown/dropDown.tsx
Labels: refactoring ⌨️

#448 Feat/multiselect dropdown
  src/ui/component/dropDown/dropDown.tsx
  src/ui/component/dropDown/multiselectDropDown.scss
  src/ui/component/dropDown/multiselectDropDown.tsx
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.scss
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
Labels: feature 🤌

#450 Feat/multiselect dropdown modal
  src/ui/component/dropDown/multiselectDropDown.scss
  src/ui/component/dropDown/multiselectDropDown.tsx
  src/ui/component/modal/modal.tsx
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
  src/ui/view/modal/okp4-modal.tsx
Labels: feature 🤌

#453 Feat/dropdown for topic and geocov
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
Labels: feature 🤌

#419 Feat/add share dataset summary
  src/ui/asset/images/know-token.webp
  src/ui/page/share/dataset/shareDataset.tsx
  src/ui/page/share/dataset/steps/summary/summary.scss
  src/ui/page/share/dataset/steps/summary/summary.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
  src/ui/style/palette.scss
  src/ui/style/theme.scss
Labels: feature 🤌

#451 feat(governance): add paragraph see more modal pop up
  src/ui/component/button/button.scss
  src/ui/view/governance/details/details.scss
  src/ui/view/governance/details/details.tsx
  src/ui/view/modal/okp4-modal.scss
Labels: enhancement 💯
