Repository okp4/dataverse-portal, pull requests merged in 2023-06, with the labels that each got.

#266 Feat/text highlighter component
  src/ui/component/textHighlighter/textHighlighter.tsx
  src/util/splitTextWithTerm/splitTextWithTerm.spec.ts
  src/util/splitTextWithTerm/splitTextWithTerm.ts
Labels: feature 🤌

#264 Feat/add share page
  src/ui/asset/images/share-dataset.webp
  src/ui/asset/images/share-service.webp
  src/ui/component/sidebar/navigation/navigation.tsx
  src/ui/page/share/i18n/index.ts
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
  src/ui/page/share/share.scss
  src/ui/page/share/share.tsx
  src/ui/routes.tsx
Labels: feature 🤌

#267 fix: update dataverse items data in explore page
  src/ui/page/home/explore/explore.tsx
Labels: bug 🐞

#275 Feat: Dataverse domain enhancements
  src/infra/dataverse/sparql/dto.ts
  src/infra/dataverse/sparql/sparqlGateway.ts
  src/ui/page/dataverse/dataverse.tsx
Labels: enhancement 💯

#262 Feat/dataverse selection filter
  src/ui/asset/icon/large-magnifier-with-cross.svg
  src/ui/component/dropDown/dropDown.scss
  src/ui/component/icon/icon.tsx
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/main.scss
  src/ui/page/dataverse/dataverse.scss
  src/ui/page/dataverse/dataverse.tsx
  src/ui/style/mixins.scss
  src/ui/style/palette.scss
  src/ui/style/theme.scss
  src/ui/view/dataverse/component/dynamicCheckbox/dynamicCheckbox.scss
  src/ui/view/dataverse/component/dynamicCheckbox/dynamicCheckbox.tsx
  src/ui/view/dataverse/component/filters/i18n/filters_de.json
  src/ui/view/dataverse/component/filters/i18n/filters_en.json
  src/ui/view/dataverse/component/filters/i18n/filters_fr.json
  src/ui/view/dataverse/component/filters/i18n/index.ts
  src/ui/view/dataverse/component/filters/selectionFilter/selectionFilter.scss
  src/ui/view/dataverse/component/filters/selectionFilter/selectionFilter.tsx
  src/util/util.spec.ts
  src/util/util.ts
Labels: feature 🤌

#278 Feat: add storage service selection page
  src/ui/component/card/card.tsx
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/page/dataverse/dataverse.scss
  src/ui/page/dataverse/dataverse.tsx
  src/ui/page/home/explore/explore.tsx
  src/ui/page/share/dataset/shareDataset.scss
  src/ui/page/share/dataset/shareDataset.tsx
  src/ui/page/share/dataset/steps/serviceStorageSelection/serviceStorageSelection.scss
  src/ui/page/share/dataset/steps/serviceStorageSelection/serviceStorageSelection.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
  src/ui/page/share/share.scss
  src/ui/page/share/share.tsx
  src/ui/routes.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
  src/ui/types.ts
  src/ui/view/dataverse/component/dataverseItemCard/dataverseItemCard.tsx
  src/ui/view/dataverse/component/itemOverview/itemOverview.tsx
  src/ui/view/loadingDataverseCards/loadingDataverseCards.scss
  src/ui/view/loadingDataverseCards/loadingDataverseCards.tsx
  src/ui/view/tabs/tabs.scss
  src/ui/view/tabs/tabs.tsx
Labels: enhancement 💯

#297 Feat/improve governance page
  src/ui/page/dataverse/dataspace/governance/mockedData.ts
  src/ui/view/governance/details/details.tsx
Labels: enhancement 💯

#301 Feat: share dataset service selection
  src/ui/common.ts
  src/ui/page/dataverse/dataverse.tsx
  src/ui/page/dataverse/service/service.tsx
  src/ui/page/share/dataset/steps/serviceStorageSelection/serviceStorageSelection.scss
  src/ui/page/share/dataset/steps/serviceStorageSelection/serviceStorageSelection.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
  src/ui/types.ts
  src/ui/view/dataverse/component/dataverseItemCard/dataverseItemCard.tsx
  src/ui/view/dataverse/component/dataverseItemDetails/detailedDataverseItem.scss
  src/ui/view/dataverse/component/dataverseItemDetails/detailedDataverseItem.tsx
  src/ui/view/dataverse/component/generalMetadata/generalMetadataValue.tsx
  src/ui/view/dataverse/component/itemOverview/itemOverview.scss
  src/ui/view/dataverse/component/itemOverview/itemOverview.tsx
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.scss
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.tsx
Labels: enhancement 💯

#313 Feat/share dataset service research
  src/domain/dataverse/command.ts
  src/domain/dataverse/domain.ts
  src/domain/dataverse/port.ts
  src/domain/dataverse/query.ts
  src/domain/dataverse/valueObject.ts
  src/infra/dataverse/sparql/sparqlGateway.ts
  src/ui/page/dataverse/dataverse.tsx
  src/ui/page/share/dataset/shareDataset.scss
  src/ui/page/share/dataset/steps/serviceStorageSelection/serviceStorageSelection.scss
  src/ui/page/share/dataset/steps/serviceStorageSelection/serviceStorageSelection.tsx
  src/ui/view/dataverse/component/filters/selectionFilter/selectionFilter.scss
  src/ui/view/dataverse/component/filters/selectionFilter/selectionFilter.tsx
  src/ui/view/dataverse/component/noResultFound/noResultFound.scss
  src/ui/view/dataverse/component/noResultFound/noResultFound.tsx
Labels: enhancement 💯

#332 feat(homepage): enable share action card
  src/ui/component/card/card.scss
  src/ui/page/home/interact/interact.scss
  src/ui/page/home/interact/interact.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
Labels: enhancement 💯

#338 Feat/remove dataspaces filter and belonging
  src/ui/page/dataverse/dataset/dataset.tsx
  src/ui/page/dataverse/dataverse.tsx
  src/ui/page/dataverse/service/service.tsx
  src/ui/view/dataverse/component/dataverseItemStatCard/dataversItemStatCard.scss
  src/ui/view/dataverse/component/dataverseItemStatCard/dataverseItemStatCard.tsx
  src/ui/view/dataverse/component/filters/i18n/filters_de.json
  src/ui/view/dataverse/component/filters/i18n/filters_en.json
  src/ui/view/dataverse/component/filters/i18n/filters_fr.json
  src/ui/view/dataverse/component/pageTemplate/i18n/index.ts
  src/ui/view/dataverse/component/pageTemplate/i18n/pageTemplate_de.json
  src/ui/view/dataverse/component/pageTemplate/i18n/pageTemplate_en.json
  src/ui/view/dataverse/component/pageTemplate/i18n/pageTemplate_fr.json
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.scss
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.tsx
  src/ui/view/dataverse/component/summaryMetadata/i18n/metadata_de.json
  src/ui/view/dataverse/component/summaryMetadata/i18n/metadata_en.json
  src/ui/view/dataverse/component/summaryMetadata/i18n/metadata_fr.json
  src/ui/view/dataverse/component/summaryMetadata/summaryMetadata.tsx
Labels: enhancement 💯

#339 refactor(dataverse): update data space description with zone
  src/ui/page/dataverse/dataverse.tsx
Labels: refactoring ⌨️

#329 feat: add unsupported feature page
  src/ui/asset/images/unsupported-feature.webp
  src/ui/page/share/share.scss
  src/ui/page/share/share.tsx
  src/ui/view/unsupportedFeature/i18n/index.ts
  src/ui/view/unsupportedFeature/i18n/unsupportedFeature_de.json
  src/ui/view/unsupportedFeature/i18n/unsupportedFeature_en.json
  src/ui/view/unsupportedFeature/i18n/unsupportedFeature_fr.json
  src/ui/view/unsupportedFeature/unsupportedFeature.scss
  src/ui/view/unsupportedFeature/unsupportedFeature.tsx
Labels: feature 🤌

#314 Feat/stepper
  package.json
  pnpm-lock.yaml
  src/ui/asset/icon/forward.svg
  src/ui/component/icon/icon.tsx
  src/ui/component/stepper/stepper.scss
  src/ui/component/stepper/stepper.tsx
  src/ui/component/stepper/stepperActions/stepperActions.scss
  src/ui/component/stepper/stepperActions/stepperActions.tsx
  src/ui/component/stepper/stepperProgress/progressBar/progressBar.tsx
  src/ui/component/stepper/stepperProgress/stepperProgress.tsx
  src/ui/component/stepper/useStepper.ts
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/style/palette.scss
  src/ui/style/theme.scss
  src/util/type.ts
Labels: feature 🤌

#342 feat: add stepper basis
  src/ui/component/stepper/stepper.scss
  src/ui/page/share/dataset/shareDataset.tsx
Labels: feature 🤌

#347 Feat/add data selection
  src/ui/asset/icon/bin.svg
  src/ui/asset/icon/folder-outlined-shadow.svg
  src/ui/asset/icon/folder-outlined.svg
  src/ui/component/filePicker/filePicker.tsx
  src/ui/component/icon/icon.tsx
  src/ui/component/list/list.scss
  src/ui/component/stepper/stepper.scss
  src/ui/page/share/dataset/shareDataset.tsx
  src/ui/page/share/dataset/steps/dataSelection/dataSelection.scss
  src/ui/page/share/dataset/steps/dataSelection/dataSelection.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
  src/ui/store/index.ts
Labels: feature 🤌

#352 Feat/add feature not available layout
  src/ui/component/router/appRouter.tsx
  src/ui/page/share/share.tsx
  src/ui/routes.tsx
  src/ui/view/unsupportedFeatureLayout/unsupportedFeatureLayout.tsx
Labels: feature 🤌
