Repository okp4/dataverse-portal, pull requests merged in 2023-04, with the labels that each got.

#153 Feat: add max width to portal page to avoid stretched elements
  src/ui/main.scss
Labels: enhancement 💯

#149 Feat/data space governance description
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/page/dataverse/dataspace/dataspace.tsx
  src/ui/page/dataverse/dataverse.tsx
  src/ui/view/dataverse/component/governanceDescription/governanceDescription.scss
  src/ui/view/dataverse/component/governanceDescription/governanceDescription.tsx
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.tsx
Labels: feature 🤌

#171 Feat/add data space resource cards
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/page/dataverse/dataverse.scss
  src/ui/page/dataverse/dataverse.tsx
  src/ui/page/home/home.scss
  src/ui/style/mixins.scss
  src/ui/view/dataverse/component/dataverseItemStatCard/dataversItemStatCard.scss
  src/ui/view/dataverse/component/dataverseItemStatCard/dataverseItemStatCard.tsx
  src/ui/view/dataverse/component/pageTemplate/i18n/index.ts
  src/ui/view/dataverse/component/pageTemplate/i18n/pageTemplate_de.json
  src/ui/view/dataverse/component/pageTemplate/i18n/pageTemplate_en.json
  src/ui/view/dataverse/component/pageTemplate/i18n/pageTemplate_fr.json
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.scss
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.tsx
Labels: feature 🤌, refactoring ⌨️

#174 Feat: add general and audit metadata part
  src/ui/asset/icon/check.svg
  src/ui/asset/icon/copy-dark.svg
  src/ui/asset/icon/copy-light.svg
  src/ui/asset/icon/error.svg
  src/ui/asset/icon/info-dark.svg
  src/ui/asset/icon/info-light.svg
  src/ui/asset/icon/warning.svg
  src/ui/component/copyToClipboard/copyToClipboard.scss
  src/ui/component/copyToClipboard/copyToClipboard.tsx
  src/ui/component/icon/icon.tsx
  src/ui/component/toast/toast.scss
  src/ui/component/toast/toast.tsx
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/page/dataverse/dataset/dataset.tsx
  src/ui/page/dataverse/dataspace/dataspace.tsx
  src/ui/page/dataverse/service/service.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
  src/ui/view/dataverse/component/generalMetadata/generalMetadata.tsx
  src/ui/view/dataverse/component/pageTemplate/pageTemplate.tsx
  src/ui/view/dataverse/component/summaryMetadata/i18n/index.ts
  src/ui/view/dataverse/component/summaryMetadata/i18n/metadata_de.json
  src/ui/view/dataverse/component/summaryMetadata/i18n/metadata_en.json
  src/ui/view/dataverse/component/summaryMetadata/i18n/metadata_fr.json
  src/ui/view/dataverse/component/summaryMetadata/summaryMetadata.scss
  src/ui/view/dataverse/component/summaryMetadata/summaryMetadata.tsx
  src/ui/view/dataverse/types.ts
Labels: enhancement 💯

#184 refactor: improve syntax
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/page/home/i18n/home_de.json
  src/ui/page/home/i18n/home_en.json
  src/ui/page/home/i18n/home_fr.json
Labels: enhancement 💯

#209 fix: make dataverse back button text clickable
  src/ui/view/dataverse/component/backButton/backButton.scss
  src/ui/view/dataverse/component/backButton/backButton.tsx
Labels: enhancement 💯
