Repository okp4/dataverse-portal, pull requests merged in 2023-09, with the labels that each got.

#457 Feat/improve tags field scrollbar display
  src/ui/view/tagsField/tagsField.scss
  src/ui/view/tagsField/tagsField.tsx
Labels: enhancement 💯

#461 Feat/disabled button state
  src/ui/component/button/button.scss
  src/ui/component/stepper/stepperActions/stepperActions.scss
  src/ui/style/palette.scss
  src/ui/style/theme.scss
Labels: bug 🐞, enhancement 💯

#460 Feat/datepicker component
  src/ui/component/dateInput/dateInput.scss
  src/ui/component/dateInput/dateInput.tsx
  src/ui/component/datePicker/datePicker.tsx
  src/ui/component/dayPicker/dayPicker.tsx
  src/ui/component/dropDown/dropDown.scss
  src/ui/component/dropDown/dropDown.tsx
  src/ui/component/popover/popover.scss
  src/ui/component/popover/popover.tsx
  src/util/date/date.spec.ts
  src/util/date/date.ts
Labels: feature 🤌

#463 Feat/dateRangePicker component
  src/ui/component/datePicker/datePicker.tsx
  src/ui/component/dateRangePicker/dateRangePicker.scss
  src/ui/component/dateRangePicker/dateRangePicker.tsx
  src/ui/component/dayPicker/dayPicker.scss
  src/ui/component/dayPicker/dayPicker.tsx
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/style/palette.scss
  src/ui/view/dataverse/component/generalMetadata/dateInterval.tsx
Labels: feature 🤌

#477 fix(metadataFilling): separate tag functions add & delete concerns
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
Labels: bug 🐞

#482 fix(dataverse): add missing zones data
  src/ui/page/dataverse/dataverse.tsx
Labels: bug 🐞

#469 Feat/date range field
  public/assets/env.js
  src/env.d.ts
  src/ui/component/dropDown/dropDown.scss
  src/ui/component/tag/tag.scss
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.scss
  src/ui/page/share/dataset/steps/metadataFilling/metadataFilling.tsx
  src/ui/page/share/dataset/steps/summary/summary.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
  src/ui/store/slice/shareData/shareData.slice.ts
  src/ui/store/slice/shareData/test/shareDataSlice.spec.ts
  src/ui/view/share/knowFee/knowFee.scss
  src/ui/view/tagsField/tagsField.scss
  src/util/date/date.spec.ts
  src/util/date/date.ts
Labels: feature 🤌

#473 Feat/date range filter
  src/ui/page/dataverse/dataverse.tsx
  src/ui/view/dataverse/component/filters/dateRangeFilter/dateRangeFilter.scss
  src/ui/view/dataverse/component/filters/dateRangeFilter/dateRangeFilter.tsx
  src/ui/view/dataverse/component/filters/filter.scss
  src/ui/view/dataverse/component/filters/filter.tsx
  src/ui/view/dataverse/component/filters/selectionFilter/selectionFilter.scss
  src/ui/view/dataverse/component/filters/selectionFilter/selectionFilter.tsx
Labels: feature 🤌

#484 Feat/create share data step 5
  public/assets/env.js
  src/env.d.ts
  src/ui/asset/icon/info-outlined-dark.svg
  src/ui/asset/icon/info-outlined-light.svg
  src/ui/asset/icon/keplr.svg
  src/ui/component/icon/icon.tsx
  src/ui/page/share/dataset/shareDataset.tsx
  src/ui/page/share/dataset/steps/completeTransaction/completeTransaction.scss
  src/ui/page/share/dataset/steps/completeTransaction/completeTransaction.tsx
  src/ui/page/share/i18n/share_de.json
  src/ui/page/share/i18n/share_en.json
  src/ui/page/share/i18n/share_fr.json
  src/ui/style/theme.scss
Labels: feature 🤌

#486 Refactor/popover component props
  src/ui/component/popover/popover.tsx
Labels: enhancement 💯

#487 Fix/popover component
  src/ui/component/popover/popover.tsx
Labels: bug 🐞
