Repository okp4/dataverse-portal, pull requests merged in 2023-05, with the labels that each got.

#198 Feat/handle rendering error
  public/assets/env.js
  src/env.d.ts
  src/ui/App.tsx
  src/ui/asset/images/internal-error-dark-mobile.webp
  src/ui/asset/images/internal-error-dark.webp
  src/ui/asset/images/internal-error-light-mobile.webp
  src/ui/asset/images/internal-error-light.webp
  src/ui/component/button/button.scss
  src/ui/component/button/button.tsx
  src/ui/component/errorBoundary/errorBoundary.tsx
  src/ui/page/internalError/i18n/index.tsx
  src/ui/page/internalError/i18n/internalError_de.json
  src/ui/page/internalError/i18n/internalError_en.json
  src/ui/page/internalError/i18n/internalError_fr.json
  src/ui/page/internalError/internalError.scss
  src/ui/page/internalError/internalError.tsx
Labels: feature 🤌

#202 Feat/error page routing
  src/ui/asset/images/not-found-error-dark-mobile.webp
  src/ui/asset/images/not-found-error-dark.webp
  src/ui/asset/images/not-found-error-light-mobile.webp
  src/ui/asset/images/not-found-error-light.webp
  src/ui/page/dataverse/dataset/dataset.tsx
  src/ui/page/dataverse/dataspace/dataspace.tsx
  src/ui/page/dataverse/dataspace/governance/governance.tsx
  src/ui/page/dataverse/service/service.tsx
  src/ui/page/notFoundError/i18n/index.tsx
  src/ui/page/notFoundError/i18n/notFoundError_de.json
  src/ui/page/notFoundError/i18n/notFoundError_en.json
  src/ui/page/notFoundError/i18n/notFoundError_fr.json
  src/ui/page/notFoundError/notFoundError.scss
  src/ui/page/notFoundError/notFoundError.tsx
  src/ui/routes.tsx
Labels: feature 🤌

#233 Refactor/error-pages
  src/ui/component/errorBoundary/errorBoundary.tsx
  src/ui/page/dataverse/dataset/dataset.tsx
  src/ui/page/dataverse/dataspace/dataspace.tsx
  src/ui/page/dataverse/dataspace/governance/governance.tsx
  src/ui/page/dataverse/service/service.tsx
  src/ui/page/error/error.scss
  src/ui/page/error/i18n/error_de.json
  src/ui/page/error/i18n/error_en.json
  src/ui/page/error/i18n/error_fr.json
  src/ui/page/error/i18n/index.tsx
  src/ui/page/error/internalError/internalError.scss
  src/ui/page/error/internalError/internalError.tsx
  src/ui/page/error/notFoundError/notFoundError.scss
  src/ui/page/error/notFoundError/notFoundError.tsx
  src/ui/page/internalError/i18n/index.tsx
  src/ui/page/internalError/i18n/internalError_de.json
  src/ui/page/internalError/i18n/internalError_en.json
  src/ui/page/internalError/i18n/internalError_fr.json
  src/ui/page/internalError/internalError.scss
  src/ui/page/internalError/internalError.tsx
  src/ui/page/notFoundError/i18n/index.tsx
  src/ui/page/notFoundError/i18n/notFoundError_de.json
  src/ui/page/notFoundError/i18n/notFoundError_en.json
  src/ui/page/notFoundError/i18n/notFoundError_fr.json
  src/ui/page/notFoundError/notFoundError.scss
  src/ui/page/notFoundError/notFoundError.tsx
  src/ui/routes.tsx
Labels: refactoring ⌨️

#221 Feat/add wallet connection
  package.json
  pnpm-lock.yaml
  public/assets/env.js
  src/domain/wallet/command.ts
  src/domain/wallet/domain.ts
  src/domain/wallet/entity.ts
  src/domain/wallet/port.ts
  src/domain/wallet/query.ts
  src/env.d.ts
  src/infra/wallet/keplrGateway.ts
  src/infra/wallet/window.d.ts
  src/ui/asset/icon/expand-down-dark.svg
  src/ui/asset/icon/expand-down-light.svg
  src/ui/asset/icon/keplr.svg
  src/ui/asset/icon/log-out.svg
  src/ui/component/button/button.tsx
  src/ui/component/icon/icon.tsx
  src/ui/component/notification/i18n/notification_de.json
  src/ui/component/notification/i18n/notification_en.json
  src/ui/component/notification/i18n/notification_fr.json
  src/ui/component/notification/notification.tsx
  src/ui/component/toast/toast.tsx
  src/ui/component/toolbar/i18n/toolbar_de.json
  src/ui/component/toolbar/i18n/toolbar_en.json
  src/ui/component/toolbar/i18n/toolbar_fr.json
  src/ui/component/toolbar/toolbar.scss
  src/ui/component/toolbar/toolbar.tsx
  src/ui/hook/useDispatchNotification.ts
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/store/index.ts
  src/ui/style/mixins.scss
  src/ui/style/theme.scss
  src/ui/view/governance/details/details.scss
  src/util/util.ts
Labels: enhancement 💯

#254 fix: update headScripts async to false in html-config
  config/html-config.ts
Labels: bug 🐞

#250 Fix/error page flashing on dataverse item card selection
  src/ui/page/dataverse/dataset/dataset.tsx
  src/ui/page/dataverse/dataspace/dataspace.tsx
  src/ui/page/dataverse/service/service.tsx
Labels: bug 🐞

#258 Feat/searchbar component
  src/ui/asset/icon/magnifier.svg
  src/ui/component/icon/icon.tsx
  src/ui/component/searchbar/searchbar.scss
  src/ui/component/searchbar/searchbar.tsx
Labels: feature 🤌

#265 Fix/Wallet button on page refresh
  src/domain/wallet/domain.ts
Labels: bug 🐞

#260 Feat/checkbox component
  package.json
  pnpm-lock.yaml
  src/ui/asset/icon/checkbox.svg
  src/ui/component/checkbox/checkbox.scss
  src/ui/component/checkbox/checkbox.tsx
  src/ui/component/icon/icon.tsx
  src/ui/style/palette.scss
  src/ui/style/theme.scss
Labels: feature 🤌

#222 Feat/mobile governance page
  src/ui/component/dropDown/dropDown.scss
  src/ui/component/dropDown/dropDown.tsx
  src/ui/i18n/translations/common_de.json
  src/ui/i18n/translations/common_en.json
  src/ui/i18n/translations/common_fr.json
  src/ui/page/dataverse/dataspace/governance/governance.scss
  src/ui/page/dataverse/dataspace/governance/governanceNavigation.tsx
  src/ui/page/dataverse/dataverse.scss
  src/ui/style/mixins.scss
  src/ui/style/theme.scss
  src/ui/view/governance/details/details.scss
  src/ui/view/governance/details/details.tsx
Labels: enhancement 💯, feature 🤌
