Repository okp4/dataverse-portal, pull requests merged in 2023-03, with the labels that each got.

#89 Fix: Size of the sidebar changes according to the chosen language
  src/component/sidebar/sidebar.scss
  src/main.scss
Labels: bug

#93 Feat: disable unavailable links on lateral bar
  src/component/sidebar/navigation/navigation.scss
  src/component/sidebar/navigation/navigation.tsx
  src/component/sidebar/sidebar.scss
  src/component/sidebar/sidebar.tsx
  src/routes.tsx
Labels: enhancement

#94 Feat/add home page participants stat
  src/component/card/card.tsx
  src/domain/stats/aggregate.ts
  src/page/home/community/community.scss
  src/page/home/community/community.tsx
  src/page/home/home.scss
  src/page/home/home.tsx
  src/page/home/i18n/home_en.json
Labels: enhancement

#95 feat(home): add french and german translations
  src/page/home/i18n/home_de.json
  src/page/home/i18n/home_fr.json
  src/page/home/i18n/index.ts
Labels: enhancement

#101 fix(card): remove card dimension restrictions
  src/component/card/card.scss
  src/page/home/community/community.scss
Labels: bug

#103 Feat/homepage community block mobile & tablet view
  src/page/home/community/community.scss
  src/page/home/home.scss
Labels: enhancement

#113 Feat/add home page interact
  src/asset/images/applications-tree.webp
  src/asset/images/data-services-tree.webp
  src/asset/images/data-spaces-tree.webp
  src/asset/images/knowledge-tree.webp
  src/component/card/card.scss
  src/component/card/card.tsx
  src/page/home/home.scss
  src/page/home/home.tsx
  src/page/home/i18n/home_de.json
  src/page/home/i18n/home_en.json
  src/page/home/i18n/home_fr.json
  src/page/home/interact/interact.scss
  src/page/home/interact/interact.tsx
  src/style/palette.scss
  src/style/theme.scss
Labels: feature 🤌

#118 feat(layout): fix sidebar & toolbar position in viewport
  src/App.tsx
  src/component/sidebar/navigation/navigation.scss
  src/component/toolbar/toolbar.scss
  src/main.scss
Labels: enhancement 💯

#124 fix(homepage): fix translations
  src/page/home/i18n/home_de.json
  src/page/home/i18n/home_fr.json
Labels: bug 🐞

#121 refactor(dataverse): create card component
  src/component/card/dataverseCard/dataverseCard.scss
  src/component/card/dataverseCard/dataverseCard.tsx
  src/component/tag/tag.tsx
  src/page/dataverse/dataverse.scss
  src/page/dataverse/dataverse.tsx
Labels: enhancement 💯, refactoring ⌨️

#129 Style/align dataverse card with mock up
  src/component/button/button.scss
  src/component/card/dataverseCard/dataverseCard.scss
Labels: enhancement 💯

#130 Fix: update grid space management from auto fit to auto fill
  src/page/dataverse/dataverse.scss
Labels: bug 🐞

#133 refactor: update all responsive functions to use use-breakpoints() func
  src/component/card/dataverseCard/dataverseCard.scss
  src/component/chip/chip.scss
  src/component/sidebar/sidebar.scss
  src/component/toolbar/toolbar.scss
  src/main.scss
  src/page/dataverse/dataverse.scss
  src/page/home/community/community.scss
  src/page/home/explore/explore.scss
  src/page/home/home.scss
  src/page/home/interact/interact.scss
  src/page/workInProgress/workInProgress.scss
  src/style/mixins.scss
Labels: enhancement 💯, refactoring ⌨️

#135 Fix/no scroll on small screen
  src/component/sidebar/sidebar.scss
  src/component/sidebar/sidebar.tsx
  src/main.scss
Labels: bug 🐞

#136 Style/add layout mixins
  src/component/toolbar/toolbar.scss
  src/main.scss
  src/page/dataverse/dataverse.scss
  src/page/home/home.scss
  src/style/mixins.scss
Labels: enhancement 💯, refactoring ⌨️

#137 fix(app): toolbar disappears on mobile scroll
  src/App.tsx
  src/main.scss
Labels: bug 🐞

#139 fix(chip): text wrapping on small screen
  src/component/chip/chip.scss
  src/page/dataverse/dataverse.scss
Labels: bug 🐞

#148 Feat/button size property
  src/ui/component/button/button.scss
  src/ui/component/button/button.tsx
  src/ui/component/toolbar/toolbar.tsx
  src/ui/page/dataverse/dataverse.tsx
  src/ui/page/home/explore/explore.tsx
Labels: enhancement 💯, feature 🤌
